config/routes.rb
SimpleCms::Application.routes.draw do
  resources :champions
  resources :random, :only => [:index]
  match '/random/generate_random', {:action => :new_random, :controller => :random, :via => :get}
  root :to => "random#main"
  
end

app/models/champion.rb
class Champion < ActiveRecord::Base
  attr_accessible :guide_url, :image_url, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  # GET /champions
  # GET /champions.json
  def index
    @champions = Champion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @champions }
    end
  end

  # GET /champions/1
  # GET /champions/1.json
  def show
    @champion = Champion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @champion }
    end
  end

  # GET /champions/new
  # GET /champions/new.json
  def new
    @champion = Champion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @champion }
    end
  end

  # GET /champions/1/edit
  def edit
    @champion = Champion.find(params[:id])
  end

  # POST /champions
  # POST /champions.json
  def create
    @champion = Champion.new(params[:champion])

    respond_to do |format|
      if @champion.save
        format.html { redirect_to @champion, :notice => 'Champion was successfully created.' }
        format.json { render :json => @champion, :status => :created, :location => @champion }
      else
        format.html { render :action => "new" }
        format.json { render :json => @champion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /champions/1
  # PUT /champions/1.json
  def update
    @champion = Champion.find(params[:id])

    respond_to do |format|
      if @champion.update_attributes(params[:champion])
        format.html { redirect_to @champion, :notice => 'Champion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @champion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /champions/1
  # DELETE /champions/1.json
  def destroy
    @champion = Champion.find(params[:id])
    @champion.destroy

    respond_to do |format|
      format.html { redirect_to champions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/random_controller.rb
class RandomController < ApplicationController
before_filter :get_random,:only => [:index, :new_random]
def index
	
end
def new_random
	
end
private
def get_random
	@champion=Champion.find(rand(Champion.count) + 1)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/random_helper.rb
module RandomHelper
end

app/views/champions/_form.html.erb
<%= form_for(@champion) do |f| %>
  <% if @champion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@champion.errors.count, "error") %> prohibited this champion from being saved:</h2>

      <ul>
      <% @champion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :guide_url %><br />
    <%= f.text_field :guide_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/champions/edit.html.erb
<h1>Editing champion</h1>

<%= render 'form' %>

<%= link_to 'Show', @champion %> |
<%= link_to 'Back', champions_path %>

app/views/champions/index.html.erb
<h1>Listing champions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image url</th>
    <th>Guide url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @champions.each do |champion| %>
  <tr>
    <td><%= champion.name %></td>
    <td><%= champion.image_url %></td>
    <td><%= champion.guide_url %></td>
    <td><%= link_to 'Show', champion %></td>
    <td><%= link_to 'Edit', edit_champion_path(champion) %></td>
    <td><%= link_to 'Destroy', champion, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Champion', new_champion_path %>

app/views/champions/new.html.erb
<h1>New champion</h1>

<%= render 'form' %>

<%= link_to 'Back', champions_path %>

app/views/champions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @champion.name %>
</p>

<p>
  
  <%= image_tag @champion.image_url %>
</p>

<p>
  <b>Guide url:</b>
  
  <%= link_to "Link to #{@champion.name}'s guide", @champion.guide_url %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleCms</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/random/_champion.erb
<p>
  <b>Name:</b>
  <%= @champion.name %>
</p>

<p>
  
  <%= image_tag @champion.image_url %>
</p>

<p>
  <b>Guide url:</b>
  
  <%= link_to "Link to #{@champion.name}'s guide", @champion.guide_url %>
</p>

app/views/random/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "Fetch Random Champion!", random_generate_random_path, :remote => true %>
<div id="random_champion">
	<%= render 'random/champion' %>
</div>

app/views/random/main.html.erb
<%= link_to "Fetch Random Champion!", random_generate_random_path, :remote => true %>
<div id="random_champion">
</div>

app/views/random/new_random.js.erb
$("#random_champion").html("<%= escape_javascript(render 'random/champion') %>");